language: ruby
rvm:
  - 2.2.2
matrix:
  include:
  - rvm: rbx-2.6
    env: RBX_RUBY_COMPAT=2.1.0 RBX_VERSION=2.6
bundler_args: --without production --without development --jobs=4
cache: bundler
before_install:
  - 'echo "gem: --no-ri --no-rdoc" > ~/.gemrc'
before_script:
  - psql -c 'create user levelup with superuser;' -U postgres
  - bundle exec rake db:{create,migrate}
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - SECRET_KEY=f2fbcc06ac38f6f3a6383045f25856d
